In [50]:
import pandas as pd 
import numpy as np


In [51]:
df=pd.read_csv("D:/MACHINE  LEARNING/Machine learning using Python/cars.csv")

In [52]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [53]:
df.sample(5)

brand  km_driven    fuel         owner  selling_price
6347   Mahindra     100000  Diesel  Second Owner         121000
5736    Hyundai     190000  Diesel   Third Owner         250000
7902     Toyota     120000  Diesel   First Owner        1100000
5550  Chevrolet      32000  Diesel   First Owner         535000
4035     Maruti      30000  Diesel   First Owner         580000

In [54]:
df['brand'].value_counts().sum()

np.int64(8128)

In [55]:
df['brand'].nunique()

32

In [56]:
df['fuel'].nunique()


4

In [57]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [58]:
df['owner'].nunique()

5

In [59]:
print(df.dtypes)


brand            object
km_driven         int64
fuel             object
owner            object
selling_price     int64
dtype: object


## 1 OneHOtEncoding Using pAndas 

In [60]:
df_encoded = pd.get_dummies(df, columns=['fuel', 'owner'])
df_encoded = df_encoded.apply(lambda col: col.astype(int) if col.dtype == 'bool' else col)


In [61]:
df_encoded.head()


brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0   Maruti     145500         450000         0            1         0   
1    Skoda     120000         370000         0            1         0   
2    Honda     140000         158000         0            0         0   
3  Hyundai     127000         225000         0            1         0   
4   Maruti     120000         130000         0            0         0   

   fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0            0                  1                           0   
1            0                  0                           0   
2            1                  0                           0   
3            0                  1                           0   
4            1                  1                           0   

   owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                   0                     0                  0  
1                   1                     0                  0  
2                   0                     0                  1  
3                   0                     0                  0  
4                   0                     0                  0

# n-1 (solve multicollinearity problem)

In [62]:
df_encoded = pd.get_dummies(df, columns=['fuel', 'owner'],drop_first=True)
df_encoded = df_encoded.apply(lambda col: col.astype(int) if col.dtype == 'bool' else col)

In [63]:
df_encoded.head()

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0   Maruti     145500         450000            1         0            0   
1    Skoda     120000         370000            1         0            0   
2    Honda     140000         158000            0         0            1   
3  Hyundai     127000         225000            1         0            0   
4   Maruti     120000         130000            0         0            1   

   owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                           0                   0                     0   
1                           0                   1                     0   
2                           0                   0                     0   
3                           0                   0                     0   
4                           0                   0                     0   

   owner_Third Owner  
0                  0  
1                  0  
2                  1  
3                  0  
4                  0

# pandas dont remember which column is is what positioned if you do again it will generate different result therefore you not able to apply this on machine learning project so thats why use scikit learner encoder class

# 3 ONEHotCoding using scikit learn

In [64]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2,random_state=2)

In [66]:
from sklearn.preprocessing import OneHotEncoder

In [67]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np  # Make sure numpy is imported

ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)


In [68]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [69]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Ensure correct column selection
X_train, X_test, y_train, y_test = train_test_split(df[['brand', 'km_driven', 'fuel', 'owner']], df['selling_price'], test_size=0.2, random_state=2)

# Initialize encoder
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

# Fit-transform the categorical columns
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])

print(X_train_new)  # Check the transformed data


[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 [1 0 0 ... 0 0 0]]


In [70]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [71]:
print(X_train.columns)


Index(['brand', 'km_driven', 'fuel', 'owner'], dtype='object')


In [72]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [73]:
X_train_new.shape

(6502, 7)

In [74]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [75]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

## one hot coding with Top Categories 

In [76]:
counts = df['brand'].value_counts()

In [77]:
df['brand'].nunique()
threshold = 100

In [78]:
repl = counts[counts <= threshold].index

In [79]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

BMW  Chevrolet   Ford  Honda  Hyundai  Mahindra  Maruti  Renault  \
4125  False      False  False  False    False     False    True    False   
3133  False      False  False  False    False     False    True    False   
5249  False      False  False  False    False     False   False    False   
2803  False      False  False  False    False     False    True    False   
768   False      False  False  False    False     False    True    False   

      Skoda   Tata  Toyota  Volkswagen  uncommon  
4125  False  False   False       False     False  
3133  False  False   False       False     False  
5249  False  False    True       False     False  
2803  False  False   False       False     False  
768   False  False   False       False     False

In [80]:
df_encoded = pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)
df_encoded = df_encoded.apply(lambda col: col.astype(int) if col.dtype == 'bool' else col)

In [82]:
df_encoded.head()

BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  \
2777    0          0     0      0        1         0       0        0      0   
7135    0          0     0      0        0         0       1        0      0   
1074    0          0     0      0        1         0       0        0      0   
5904    0          0     0      1        0         0       0        0      0   
6143    0          0     1      0        0         0       0        0      0   

      Tata  Toyota  Volkswagen  uncommon  
2777     0       0           0         0  
7135     0       0           0         0  
1074     0       0           0         0  
5904     0       0           0         0  
6143     0       0           0         0